### PR TITLE
Fix the card overlapping issue

### PR DESCRIPTION
**Pull request by hzj010427**
## Issue
This PR addresses the issue #247. 

## Changes
- Added responsive margin classes and responsive image styling.

### CODE REVIEW

**Comment by lima-1thing** [comment]
Hi Zijie, when I view the new page using iPhone SE or Pixel 7, the layout still has issues:
image

image


Can you try to fix it?

Thanks!

**Comment by hzj010427** [comment]
> Hi Zijie, when I view the new page using iPhone SE or Pixel 7, the layout still has issues: image
> 
> image
> Can you try to fix it?
> 
> Thanks!

Hi Li, do we have mobile page design for these three projects? I can't seem to find them in Figma.

**Comment by hzj010427** [comment]
> Hi Zijie, when I view the new page using iPhone SE or Pixel 7, the layout still has issues: image
> 
> image
> Can you try to fix it?
> 
> Thanks!

Since there's no mobile page of this project in Figma, I made some quick adjustments to the mobile page.

**Comment by lima-1thing** [comment]
It still doesn't look right:
image

**Comment by hzj010427** [comment]
> It still doesn't look right: image

Fixed.

**Review by lima-1thing — APPROVED** [review]

**Review by lima-1thing — APPROVED** [review]

**Pull request merged**
